'use strict';
const {randomBytes,randomUUID}=require('node:crypto');
const {WebSocketServer,WebSocket}=require('ws');
const {Game}=require('../frontend/puyo-core.js');
const ACTIONS=new Set(['left','right','down','rotate','ccw','drop']);
class PuyoRooms{
 constructor({now=()=>Date.now(),countdown=3000,grace=15000}={}){this.now=now;this.countdown=countdown;this.grace=grace;this.rooms=new Map();}
 name(value){return String(value||'게스트').replace(/[\x00-\x1f]/g,'').trim().slice(0,16)||'게스트';}
 create(c,name){if(c.room)throw Error('현재 방을 먼저 나가주세요.');if(this.rooms.size>=100)throw Error('방이 가득 찼습니다.');let code;do{code=randomBytes(3).toString('hex').toUpperCase();}while(this.rooms.has(code));const r={code,players:[],host:null,phase:'waiting',round:0,startAt:0,last:this.now(),touched:this.now(),winner:null};this.rooms.set(code,r);this.join(c,code,name);return r;}
 join(c,code,name){if(c.room)throw Error('현재 방을 먼저 나가주세요.');const r=this.rooms.get(String(code).trim().toUpperCase());if(!r)throw Error('방 코드를 확인해주세요.');if(r.phase!=='waiting')throw Error('이미 진행 중인 방입니다.');if(r.players.length>=4)throw Error('최대 4명까지 입장할 수 있습니다.');const p={id:randomUUID(),token:randomBytes(24).toString('hex'),name:this.name(name),ready:false,client:c,game:null,seq:0,disconnected:null,sent:0,target:0,rateAt:this.now(),rateCount:0};r.players.push(p);r.host??=p.id;c.room=r;c.player=p;r.touched=this.now();return p;}
 resume(c,code,token){if(c.room)throw Error('이미 방에 입장했습니다.');const r=this.rooms.get(String(code).toUpperCase()),p=r?.players.find(p=>p.token===token);if(!p||p.client||p.disconnected===null||this.now()-p.disconnected>this.grace)throw Error('재접속 시간이 지났습니다. 다시 입장해주세요.');c.room=r;c.player=p;p.client=c;p.disconnected=null;r.touched=this.now();}
 ready(c,value){if(c.room.phase!=='waiting')throw Error('대기 중에만 준비할 수 있습니다.');c.player.ready=!!value;}
 start(c){const r=c.room;if(r.host!==c.player.id)throw Error('방장만 시작할 수 있습니다.');if(r.phase!=='waiting'||r.players.length<2||r.players.some(p=>!p.ready||!p.client))throw Error('2~4명이 모두 준비해야 합니다.');r.round++;r.seed=randomBytes(4).readUInt32LE();r.startAt=this.now()+this.countdown;r.phase='countdown';r.winner=null;r.last=r.startAt;for(const p of r.players){p.game=new Game(r.seed);p.seq=0;p.sent=0;p.target=0;}r.touched=this.now();}
 rematch(c){const r=c.room;if(r.host!==c.player.id||r.phase!=='finished')throw Error('경기 종료 후 방장이 다시 시작할 수 있습니다.');r.players=r.players.filter(p=>p.client);for(const p of r.players){p.game=null;p.ready=false;}r.phase='waiting';r.touched=this.now();}
 input(c,m){const r=c.room,p=c.player;if(r.phase!=='playing'||p.game.phase==='over')return;if(m.round!==r.round||!Number.isSafeInteger(m.seq)||m.seq<=p.seq||m.seq>p.seq+1000||!ACTIONS.has(m.action))return;const now=this.now();if(now-p.rateAt>=1000){p.rateAt=now;p.rateCount=0;}if(++p.rateCount>50)return;p.seq=m.seq;p.game.act(m.action);r.touched=now;}
 disconnect(c,leave=false){const r=c.room,p=c.player;if(!r||!p)return;c.room=null;c.player=null;p.client=null;p.disconnected=this.now();if(leave||r.phase==='waiting'){p.game?.end();if(r.phase==='waiting'||r.phase==='finished')r.players=r.players.filter(v=>v!==p);else p.disconnected=this.now()-this.grace-1;}if(r.host===p.id)r.host=r.players.find(v=>v.client)?.id||p.id;if(!r.players.some(v=>v.client)&&r.phase==='waiting')this.rooms.delete(r.code);}
 tick(){const now=this.now();for(const r of this.rooms.values()){if(now-r.touched>30*60*1000&&!r.players.some(p=>p.client)){this.rooms.delete(r.code);continue;}for(const p of r.players)if(!p.client&&p.disconnected!==null&&now-p.disconnected>=this.grace)p.game?.end();if(r.phase==='countdown'&&now>=r.startAt){r.phase='playing';r.last=r.startAt;}if(r.phase!=='playing')continue;let dt=Math.max(0,Math.min(1000,now-r.last));r.last=now;while(dt>0){const step=Math.min(50,dt);for(const p of r.players)p.game.step(step);dt-=step;}
 // Collect all attacks before delivery, so arrival order cannot favor a player.
 const deliveries=[];for(const p of r.players){const n=p.game.takeAttack();if(!n||p.game.phase==='over')continue;const opponents=r.players.filter(v=>v!==p&&v.game.phase!=='over');if(opponents.length){const target=opponents[p.target++%opponents.length];deliveries.push([target,n]);p.sent+=n;}}for(const [p,n]of deliveries)p.game.receive(n);
 const alive=r.players.filter(p=>p.game.phase!=='over');if(alive.length<=1){r.phase='finished';r.winner=alive[0]?.id||null;r.touched=now;}}
 }
 view(c){const r=c.room;return{type:'state',protocol:1,code:r.code,you:c.player.id,host:r.host,phase:r.phase,round:r.round,startAt:r.startAt,now:this.now(),winner:r.winner,players:r.players.map(p=>({id:p.id,name:p.name,ready:p.ready,connected:!!p.client,sent:p.sent,ack:p.seq,game:p.game?.snapshot()||null}))};}
}
function attachPuyo(server,{allowedOrigins=process.env.ALLOWED_ORIGINS||'',roomOptions={}}={}){
 const manager=new PuyoRooms(roomOptions),wss=new WebSocketServer({noServer:true,maxPayload:2048,perMessageDeflate:false});
 const upgrade=(req,socket,head)=>{if(req.url!=='/puyo-ws')return;const allowed=new Set(allowedOrigins.split(',').map(s=>s.trim()).filter(Boolean));allowed.add('https://pdf-page-editor.onrender.com');allowed.add('http://'+req.headers.host);allowed.add('https://'+req.headers.host);if(!allowed.has(req.headers.origin)||wss.clients.size>=200){socket.write('HTTP/1.1 403 Forbidden\r\nConnection: close\r\n\r\n');socket.destroy();return;}wss.handleUpgrade(req,socket,head,ws=>wss.emit('connection',ws));};server.on('upgrade',upgrade);
 const send=(ws,m)=>{if(ws.readyState===WebSocket.OPEN){if(ws.bufferedAmount>1024*1024){ws.close(1013);return;}ws.send(JSON.stringify(m));}};
 function broadcast(r){if(r)for(const p of r.players)if(p.client)send(p.client.ws,manager.view(p.client));}
 wss.on('connection',ws=>{const c={ws,room:null,player:null};let rateAt=Date.now(),count=0,alive=true;const timeout=setTimeout(()=>{if(!c.room)ws.close(1000,'Join timeout');},30000);ws.on('pong',()=>alive=true);ws.checkAlive=()=>{if(!alive){ws.terminate();return;}alive=false;ws.ping();};ws.on('message',(data,binary)=>{if(binary){ws.close(1003);return;}if(Date.now()-rateAt>1000){rateAt=Date.now();count=0;}if(++count>90){ws.close(1008);return;}try{const m=JSON.parse(data);if(!m||typeof m!=='object'||Array.isArray(m))throw Error('잘못된 요청입니다.');manager.tick();if(['create','join','resume'].includes(m.type)){if(m.protocol!==1)throw Error('페이지를 새로고침해주세요.');if(m.type==='create')manager.create(c,m.name);else if(m.type==='join')manager.join(c,m.code,m.name);else manager.resume(c,m.code,m.token);clearTimeout(timeout);send(ws,{type:'joined',code:c.room.code,you:c.player.id,token:c.player.token});broadcast(c.room);return;}if(!c.room)throw Error('먼저 방에 입장해주세요.');switch(m.type){case'ready':manager.ready(c,m.ready);break;case'start':manager.start(c);break;case'rematch':manager.rematch(c);break;case'input':manager.input(c,m);return;case'leave':{const r=c.room;manager.disconnect(c,true);send(ws,{type:'left'});broadcast(r);return;}default:throw Error('지원하지 않는 요청입니다.');}broadcast(c.room);}catch(e){send(ws,{type:'error',message:e.message});}});ws.on('close',()=>{clearTimeout(timeout);const r=c.room;manager.disconnect(c);broadcast(r);});ws.on('error',()=>{});});
 const sim=setInterval(()=>manager.tick(),16),states=setInterval(()=>{for(const r of manager.rooms.values())broadcast(r);},50),heart=setInterval(()=>{for(const ws of wss.clients)ws.checkAlive();},10000);
 return{manager,wss,close(){clearInterval(sim);clearInterval(states);clearInterval(heart);server.removeListener('upgrade',upgrade);for(const ws of wss.clients)ws.terminate();wss.close();}};
}
module.exports={PuyoRooms,attachPuyo};
