(function(){
 'use strict';
 const $=id=>document.getElementById(id),palette=['#ffd77e','#bcb1fa','#91d8cf','#f7a5b4'],SESSION='mongle-maze-session-v1';
 const canvas=$('maze'),ctx=canvas.getContext('2d'),tile=24,held=new Map(),positions=new Map();
 let socket=null,state=null,map=null,base=null,connected=false,session=null,offset=0,seq=0,retry=0,retryTimer=null,deadline=0,lastPacket=0,toastTimer=null,settingsKey='',rosterKey='',rankingKey='',watchKey='',scale=1,followKey='',intentional=false;
 try{session=JSON.parse(sessionStorage.getItem(SESSION)||'null');$('nickname').value=localStorage.getItem('mongle-online-name')||'';}catch{}
 const roomParam=new URLSearchParams(location.search).get('maze');if(roomParam)$('room-code').value=roomParam.toUpperCase().slice(0,6);
 function network(text){$('connection').textContent=text;}
 function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4000);}
 function saveSession(value){session=value;try{if(value)sessionStorage.setItem(SESSION,JSON.stringify(value));else sessionStorage.removeItem(SESSION);}catch{}}
 function send(value){if(socket?.readyState===WebSocket.OPEN){socket.send(JSON.stringify(value));return true;}return false;}
 function now(){return performance.now()+offset;}
 function busy(on){$('create').disabled=$('join').disabled=on;}
 function endpoint(){const u=new URL(window.BLOCK_ONLINE_SERVER||location.origin);if(!['http:','https:','ws:','wss:'].includes(u.protocol))throw Error('HTTP 주소로 페이지를 열어주세요.');u.protocol=['https:','wss:'].includes(u.protocol)?'wss:':'ws:';if(location.protocol==='https:'&&u.protocol!=='wss:')throw Error('HTTPS 게임 서버가 필요해요.');u.pathname='/maze-ws';u.search=u.hash='';return u.href;}
 function exit(message){intentional=true;clearTimeout(retryTimer);saveSession(null);held.clear();socket?.close();socket=null;connected=false;state=map=base=null;positions.clear();settingsKey=rosterKey=rankingKey=watchKey='';$('entry').hidden=false;$('room').hidden=true;busy(false);network(message||'방에서 나왔어요.');}
 function connect(request){let url;try{url=endpoint();}catch(e){toast(e.message);busy(false);return;}clearTimeout(retryTimer);busy(true);intentional=false;const ws=new WebSocket(url);socket=ws;network(request.type==='resume'?'재연결 중 · 잠시만 기다려주세요.':'미로 서버에 연결하고 있어요…');const timeout=setTimeout(()=>{if(ws===socket&&!connected)ws.close();},15000);
  ws.addEventListener('open',()=>{if(ws!==socket)return;lastPacket=performance.now();ws.send(JSON.stringify({...request,version:1}));ws.send(JSON.stringify({type:'ping',sent:performance.now()}));});
  ws.addEventListener('message',e=>{if(ws!==socket)return;lastPacket=performance.now();let m;try{m=JSON.parse(e.data);}catch{return;}
   if(m.type==='pong'){const rtt=performance.now()-m.sent;if(Number.isFinite(rtt)){offset=m.now+rtt/2-performance.now();$('latency').textContent=Math.round(rtt)+' ms';}return;}
   if(m.type==='joined'){clearTimeout(timeout);connected=true;retry=deadline=seq=0;saveSession({code:m.code,token:m.token});$('entry').hidden=true;$('room').hidden=false;network('연결됨 · 같은 미로, 같은 출발');return;}
   if(m.type==='state'&&connected){if(m.game!=='maze'||m.version!==1){exit('미로 서버와 페이지를 함께 업데이트해주세요.');return;}receive(m);return;}
   if(m.type==='left'||m.type==='expired'){exit(m.message);return;}
   if(m.type==='error'){toast(m.message);if(!connected){clearTimeout(timeout);exit(m.message);}return;}
  });
  ws.addEventListener('error',()=>network('미로 서버에 연결하지 못했어요. 서버 배포와 주소를 확인해주세요.'));
  ws.addEventListener('close',()=>{clearTimeout(timeout);if(ws!==socket||intentional)return;connected=false;held.clear();ui();if(session){deadline||=performance.now()+19000;if(performance.now()<deadline){network('재연결 중 · 이동은 멈춰 있어요.');retryTimer=setTimeout(()=>connect({type:'resume',...session}),Math.min(2500,500*Math.pow(1.5,retry++)));return;}}exit('연결을 복구하지 못했어요. 서버 주소와 배포 상태를 확인해주세요.');});
 }
 function enter(type){if(socket&&socket.readyState<2)return;const name=$('nickname').value.trim(),code=$('room-code').value.toUpperCase().trim();if(!name){toast('닉네임을 입력해주세요.');$('nickname').focus();return;}if(type==='join'&&!/^[A-F0-9]{6}$/.test(code)){toast('6자리 미로 방 코드를 입력해주세요.');return;}try{localStorage.setItem('mongle-online-name',name);}catch{}connect({type,name,code});}
 $('create').onclick=()=>enter('create');$('join').onclick=()=>enter('join');$('room-code').oninput=()=>{$('room-code').value=$('room-code').value.toUpperCase().replace(/[^A-F0-9]/g,'');};
 $('ready').onclick=()=>send({type:'ready',ready:!state.players.find(p=>p.id===state.you).ready});$('start').onclick=()=>send({type:'start'});$('rematch').onclick=()=>send({type:'rematch'});
 $('leave').onclick=()=>{if(state?.phase==='playing'&&!confirm('경기에서 나가면 미완주 처리돼요. 나갈까요?'))return;if(connected)send({type:'leave'});else exit();};
 $('giveup').onclick=()=>{if(confirm('이번 경기를 미완주로 마치고 관전할까요?')){stop();send({type:'giveup'});}};
 $('invite').onclick=async()=>{const u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('maze',state.code);try{await navigator.clipboard.writeText(u.href);toast('초대 링크를 복사했어요.');}catch{prompt('초대 링크를 복사해주세요.',u.href);}};
 $('settings-form').onsubmit=e=>{e.preventDefault();send({type:'settings',settings:{width:Number($('maze-width').value),height:Number($('maze-height').value),extreme:$('extreme').checked,items:$('items').checked}});};
 document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{const [w,h,extreme]=b.dataset.preset.split(',').map(Number);$('maze-width').value=w;$('maze-height').value=h;$('extreme').checked=!!extreme;});
 $('spectate').onchange=()=>send({type:'watch',id:$('spectate').value});$('zoom').oninput=()=>{fit();followKey='';};window.addEventListener('resize',()=>{fit();followKey='';});
 function node(tag,cls,text){const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;}
 function receive(m){const previous=state;if(!previous)offset=m.now-performance.now();if(!previous||previous.round!==m.round){seq=0;held.clear();positions.clear();map=null;base=null;$('zoom').value='1';followKey='';}state=m;seq=Math.max(seq,m.ack||0);if(m.map){map=m.map;buildBase();}if(m.phase==='waiting'){map=base=null;}if(m.phase!=='playing'||m.players.find(p=>p.id===m.you).status!=='racing')held.clear();
  for(const p of m.players){if(p.cell===null){positions.delete(p.id);continue;}const x=p.cell%m.settings.width,y=Math.floor(p.cell/m.settings.width);positions.set(p.id,{x,y,toX:x,toY:y,at:performance.now()});}
  ui();if(m.map)fit();if(m.phase==='playing'&&previous?.phase!=='playing'&&!document.hidden)canvas.focus({preventScroll:true});
 }
 function ui(){if(!state)return;const me=state.players.find(p=>p.id===state.you),waiting=state.phase==='waiting',host=state.host===state.you,finished=state.phase==='finished';$('room-label').textContent=state.code;$('members').textContent=state.players.length+' / 4명';$('lobby').hidden=!waiting;$('match').hidden=waiting;
  const key=JSON.stringify(state.settings);if(key!==settingsKey){settingsKey=key;$('maze-width').value=state.settings.width;$('maze-height').value=state.settings.height;$('extreme').checked=state.settings.extreme;$('items').checked=state.settings.items;}
  $('settings-fields').disabled=!host||!connected;$('ready').disabled=!connected;$('ready').textContent=me.ready?'준비 완료 · 취소':'준비하기 ✓';$('ready').setAttribute('aria-pressed',String(me.ready));$('start').hidden=!host;$('start').disabled=!connected||state.players.length<2||state.players.some(p=>!p.ready||!p.connected);$('lobby-hint').textContent='저장된 미로 '+state.settings.width+' × '+state.settings.height+'칸 · '+(state.settings.extreme?'극한 손전등':'전체 시야')+' · '+(state.settings.items?'귀환 상자 있음':'아이템 없음');
  const rk=JSON.stringify(state.players.map(p=>[p.id,p.name,p.ready,p.connected,state.host]));if(rk!==rosterKey){rosterKey=rk;$('roster').replaceChildren();for(const p of state.players){const seat=node('div','seat'+(p.ready?' ready':''));seat.style.borderTop='3px solid '+palette[p.color];seat.append(node('b','',p.name+(p.id===state.you?' · 나':'')),node('small','',(!p.connected?'재접속 대기':p.ready?'준비 완료':'준비 중')+(p.id===state.host?' · 방장':'')));$('roster').append(seat);}}
  $('match-mode').textContent=state.settings.extreme?'LIGHT YOUR OWN WAY':'SAME MAZE. YOUR OWN WAY.';$('match-title').textContent=finished?'모두의 탐험이 끝났어요.':me.status==='racing'?'출구에서 만나요.':'친구의 탐험을 지켜봐요.';$('map-size').textContent=state.settings.width+' × '+state.settings.height+'칸 · '+(state.settings.extreme?'손전등 모드':'전체 시야');$('move-count').textContent=me.steps+'칸 이동';
  const pk=JSON.stringify(state.players.map(p=>[p.id,p.status,p.connected,p.rank,p.finishAt]));if(pk!==rankingKey){rankingKey=pk;$('ranking').replaceChildren();const ordered=[...state.players].sort((a,b)=>(a.rank??99)-(b.rank??99));for(const p of ordered){const row=node('li','rank'),dot=node('i');dot.style.background=palette[p.color];const name=node('span','name',p.name+(p.id===state.you?' · 나':''));name.append(node('small','',!p.connected?'연결 끊김':p.status==='finished'?format(p.finishAt-state.startAt)+' 만에 도착':p.status==='dnf'?'포기 / 연결 종료':'길을 찾는 중'));row.append(dot,name,node('strong','',p.rank?p.rank+'위':p.status==='dnf'?'미완주':'…'));$('ranking').append(row);}}
  const racing=state.players.filter(p=>p.status==='racing');$('spectate-card').hidden=me.status==='racing'||!racing.length||waiting;const wk=racing.map(p=>p.id).join(',');if(wk!==watchKey){watchKey=wk;$('spectate').replaceChildren(...racing.map(p=>{const e=node('option','',p.name);e.value=p.id;return e;}));}$('spectate').value=state.watchId;$('view-label').textContent=me.status==='racing'?'내 시야':(state.players.find(p=>p.id===state.watchId)?.name||'탐험대')+' 관전';$('giveup').hidden=state.phase!=='playing'||me.status!=='racing';$('giveup').disabled=!connected;$('result').hidden=!finished;$('rematch').hidden=!host;$('rematch').disabled=!connected;
  if(finished){const winners=state.players.filter(p=>p.rank===1);$('result-title').textContent=winners.length?winners.map(p=>p.name).join(', ')+' · '+(winners.length>1?'공동 1위!':'1위!'):'이번 탐험은 모두 미완주';$('result-note').textContent=host?'재대결하면 새로운 미로를 만들어요.':'방장이 재대결을 누르면 다시 준비해주세요.';}
 }
 function format(ms){const s=Math.max(0,Math.floor(ms/1000));return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');}
 function buildBase(){base=document.createElement('canvas');base.width=canvas.width=map.width*tile;base.height=canvas.height=map.height*tile;const c=base.getContext('2d');c.fillStyle='#173a35';c.fillRect(0,0,base.width,base.height);c.strokeStyle='#87a48b';c.lineWidth=2;c.lineCap='round';c.beginPath();for(let i=0;i<map.cells.length;i++){const x=i%map.width*tile,y=Math.floor(i/map.width)*tile,v=map.cells[i];if(!(v&1)){c.moveTo(x+1,y+1);c.lineTo(x+tile-1,y+1);}if(!(v&8)){c.moveTo(x+1,y+1);c.lineTo(x+1,y+tile-1);}if(i%map.width===map.width-1){c.moveTo(x+tile-1,y);c.lineTo(x+tile-1,y+tile);}if(i>=map.width*(map.height-1)){c.moveTo(x,y+tile-1);c.lineTo(x+tile,y+tile-1);}}c.stroke();}
 function fit(){if(!map)return;const width=$('viewport').clientWidth||800,height=Math.min(innerHeight*.65,620);scale=Math.min(width/canvas.width,height/canvas.height,1.5)*Number($('zoom').value);canvas.style.width=Math.round(canvas.width*scale)+'px';canvas.style.height=Math.round(canvas.height*scale)+'px';}
 function point(cell){return{x:(cell%map.width+.5)*tile,y:(Math.floor(cell/map.width)+.5)*tile};}
 function draw(at){requestAnimationFrame(draw);if(!state||!map||!base||state.phase==='waiting')return;const counting=state.phase==='countdown',finished=state.phase==='finished',focus=point(state.focus),dark=state.settings.extreme&&!counting&&!finished;
  ctx.fillStyle='#0b1919';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.save();if(dark){ctx.beginPath();ctx.arc(focus.x,focus.y,tile*3.5,0,Math.PI*2);ctx.clip();}ctx.drawImage(base,0,0);
  const start=point(map.start);ctx.fillStyle='#acc4aa';ctx.font='bold 12px sans-serif';ctx.textAlign='center';ctx.fillText('S',start.x,start.y+4);
  for(const cell of map.traps){if(state.consumed.includes(cell))continue;const p=point(cell);ctx.fillStyle='#c77570';ctx.fillRect(p.x-6,p.y-6,12,12);ctx.fillStyle='#fff1d5';ctx.font='bold 10px sans-serif';ctx.fillText('↶',p.x,p.y+4);}
  const exit=point(map.exit),distance=Math.hypot(exit.x-focus.x,exit.y-focus.y)/tile;if(counting||finished||distance<=4){const gradient=ctx.createRadialGradient(exit.x,exit.y,0,exit.x,exit.y,tile*(1.2+.2*Math.sin(at/350)));gradient.addColorStop(0,'#ffdf8188');gradient.addColorStop(1,'#ffdf8100');ctx.fillStyle=gradient;ctx.fillRect(exit.x-48,exit.y-48,96,96);}ctx.fillStyle='#ffe293';ctx.font='bold 19px sans-serif';ctx.fillText('✦',exit.x,exit.y+7);if(counting){ctx.font='bold 10px sans-serif';ctx.fillText('EXIT',exit.x,exit.y-12);}
  const ordered=[...state.players].sort((a,b)=>Number(a.id===state.you)-Number(b.id===state.you));for(const p of ordered){if(p.cell===null||p.status==='dnf')continue;const pos=positions.get(p.id);if(!pos)continue;const t=Math.min(1,(at-pos.at)/100),x=(pos.x+(pos.toX-pos.x)*t+.5)*tile,y=(pos.y+(pos.toY-pos.y)*t+.5)*tile;ctx.save();ctx.globalAlpha=p.id===state.you?1:.45;ctx.fillStyle=palette[p.color];ctx.beginPath();ctx.arc(x,y,7,0,Math.PI*2);ctx.fill();ctx.fillStyle='#284238';ctx.fillRect(x-3,y-2,1.7,2);ctx.fillRect(x+2,y-2,1.7,2);ctx.restore();ctx.fillStyle='#e1eddb';ctx.font='8px sans-serif';ctx.fillText(p.name.slice(0,8),x,y-11);}
  if(dark){const g=ctx.createRadialGradient(focus.x,focus.y,tile*2.4,focus.x,focus.y,tile*3.5);g.addColorStop(0,'#0b191900');g.addColorStop(1,'#0b1919');ctx.fillStyle=g;ctx.fillRect(0,0,canvas.width,canvas.height);}ctx.restore();
  $('countdown').hidden=!counting;$('countdown-number').textContent=Math.max(1,Math.ceil((state.startAt-now())/1000));$('timer').textContent=format(counting?0:(finished?state.finishedAt:now())-state.startAt);$('event').textContent=state.event&&now()-state.event.at<4500?state.event.text:'';
  const key=state.round+':'+state.focus+':'+scale;if(key!==followKey){followKey=key;const v=$('viewport');v.scrollLeft=Math.max(0,focus.x*scale-v.clientWidth/2);v.scrollTop=Math.max(0,focus.y*scale-v.clientHeight/2);}
 }
 requestAnimationFrame(draw);
 function canMove(){return connected&&state?.phase==='playing'&&state.players.find(p=>p.id===state.you)?.status==='racing';}
 function direction(){return [...held.values()].at(-1)??-1;}
 function input(){if(canMove())send({type:'input',round:state.round,seq:++seq,direction:direction()});}
 function stop(){held.clear();input();}
 const keys={ArrowUp:0,KeyW:0,ArrowRight:1,KeyD:1,ArrowDown:2,KeyS:2,ArrowLeft:3,KeyA:3};
 document.addEventListener('keydown',e=>{if(keys[e.code]===undefined||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||e.target.isContentEditable||e.ctrlKey||e.metaKey||e.altKey||!canMove())return;e.preventDefault();if(!e.repeat){held.set(e.code,keys[e.code]);input();}});
 document.addEventListener('keyup',e=>{held.delete(e.code);});window.addEventListener('blur',stop);document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});
 document.querySelectorAll('[data-direction]').forEach(b=>{b.onpointerdown=e=>{if(e.button!==0||!canMove())return;e.preventDefault();b.setPointerCapture(e.pointerId);held.set('p'+e.pointerId,Number(b.dataset.direction));input();};for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,e=>{held.delete('p'+e.pointerId);});b.addEventListener('click',e=>{if(e.detail===0&&canMove())send({type:'input',round:state.round,seq:++seq,direction:Number(b.dataset.direction)});});});
 setInterval(()=>{if(socket?.readyState===WebSocket.OPEN){if(performance.now()-lastPacket>12000){socket.close();return;}send({type:'ping',sent:performance.now()});}},3000);
 if(session&&(!roomParam||session.code===roomParam.toUpperCase()))connect({type:'resume',...session});else if(session)saveSession(null);
})();
