/* Mongle Jelly: shared deterministic rules for browser and authoritative server. */
(function(root){'use strict';
const W=6,H=13,DIR=[[0,-1],[1,0],[0,1],[-1,0]],CHAIN=[0,0,8,16,32,64,96,128,160,192,224,256,288,320,352,384,416,448,480,512];
function random(seed){let s=seed>>>0||1;return ()=>{s^=s<<13;s^=s>>>17;s^=s<<5;return(s>>>0)/4294967296;};}
function cells(p){return [[p.x,p.y,p.colors[0]],[p.x+DIR[p.r][0],p.y+DIR[p.r][1],p.colors[1]]];}
function groups(board){const seen=new Set(),found=[],colors=new Set();let bonus=0;for(let y=0;y<H;y++)for(let x=0;x<W;x++){const color=board[y][x],key=y*W+x;if(color<1||color>4||seen.has(key))continue;const group=[],todo=[[x,y]];seen.add(key);while(todo.length){const [a,b]=todo.pop();group.push([a,b]);for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=a+dx,ny=b+dy,k=ny*W+nx;if(nx>=0&&nx<W&&ny>=0&&ny<H&&!seen.has(k)&&board[ny][nx]===color){seen.add(k);todo.push([nx,ny]);}}}if(group.length>=4){found.push(...group);colors.add(color);bonus+=group.length===4?0:group.length<=10?group.length-3:10;}}return{cells:found,colors:colors.size,bonus};}
class Game{
 constructor(seed=Date.now()){this.rng=random(seed);this.garbageRng=random(seed^0x9e3779b9);this.board=Array.from({length:H},()=>Array(W).fill(0));this.queue=[this.pair(),this.pair(),this.pair()];this.score=0;this.chain=0;this.maxChain=0;this.cleared=0;this.pending=0;this.attackCarry=0;this.outgoing=0;this.elapsed=0;this.phase='falling';this.timer=0;this.fall=0;this.lockTime=0;this.lockResets=0;this.marked=[];this.event={id:0,text:'준비 완료',chain:0};this.spawn();}
 pair(){return[1+Math.floor(this.rng()*4),1+Math.floor(this.rng()*4)];}
 valid(p){return cells(p).every(([x,y])=>x>=0&&x<W&&y>=0&&y<H&&!this.board[y][x]);}
 spawn(){this.active={x:2,y:1,r:0,colors:this.queue.shift()};this.queue.push(this.pair());this.fall=0;this.lockTime=0;this.lockResets=0;this.phase='falling';if(!this.valid(this.active))this.end();}
 end(){if(this.phase==='over')return;this.phase='over';this.active=null;this.event={id:this.event.id+1,text:'게임 종료',chain:this.chain};}
 ghost(){if(!this.active)return null;const p={...this.active};while(this.valid({...p,y:p.y+1}))p.y++;return p;}
 act(action){if(this.phase!=='falling')return false;let next={...this.active};if(action==='left'||action==='right'){next.x+=action==='left'?-1:1;if(!this.valid(next))return false;}else if(action==='rotate'||action==='ccw'){next.r=(next.r+(action==='rotate'?1:3))%4;let ok=false;for(const [dx,dy]of [[0,0],[-1,0],[1,0],[0,-1]]){const p={...next,x:next.x+dx,y:next.y+dy};if(this.valid(p)){next=p;ok=true;break;}}if(!ok)return false;}else if(action==='down'){next.y++;if(!this.valid(next))return false;this.score++;this.fall=0;}else if(action==='drop'){const ghost=this.ghost();this.score+=(ghost.y-this.active.y)*2;this.active=ghost;this.lock();return true;}else return false;this.active=next;if(this.lockResets<12){this.lockTime=0;this.lockResets++;}return true;}
 step(ms){if(this.phase==='over')return;ms=Math.max(0,Math.min(100,ms));this.elapsed+=ms;if(this.phase==='falling'){this.fall+=ms;const interval=Math.max(130,850-Math.floor(this.elapsed/30000)*55);if(this.fall>=interval){this.fall-=interval;if(this.valid({...this.active,y:this.active.y+1})){this.active.y++;this.lockTime=0;this.lockResets=0;}}if(!this.valid({...this.active,y:this.active.y+1})){this.lockTime+=ms;if(this.lockTime>=450)this.lock();}return;}this.timer-=ms;if(this.timer>0)return;if(this.phase==='clearing'){for(const [x,y]of this.marked)this.board[y][x]=0;this.marked=[];this.gravity();this.phase='settling';this.timer=180;}else if(this.phase==='settling')this.scan();else if(this.phase==='garbage'){this.spawn();}}
 lock(){for(const [x,y,c]of cells(this.active))this.board[y][x]=c;this.active=null;this.chain=0;this.gravity();this.phase='settling';this.timer=160;}
 gravity(){for(let x=0;x<W;x++){const stack=[];for(let y=H-1;y>=0;y--)if(this.board[y][x])stack.push(this.board[y][x]);for(let y=H-1;y>=0;y--)this.board[y][x]=stack[H-1-y]||0;}}
 attack(n){const canceled=Math.min(n,this.pending);this.pending-=canceled;this.outgoing+=n-canceled;}
 scan(){const g=groups(this.board);if(g.cells.length){this.chain++;this.maxChain=Math.max(this.maxChain,this.chain);this.cleared+=g.cells.length;const mult=Math.max(1,Math.min(999,(CHAIN[Math.min(this.chain,19)]||0)+[0,0,3,6,12][g.colors]+g.bonus)),points=g.cells.length*10*mult;this.score+=points;this.attackCarry+=points;this.attack(Math.floor(this.attackCarry/70));this.attackCarry%=70;const marked=new Map(g.cells.map(([x,y])=>[y*W+x,[x,y]]));for(const [x,y]of g.cells)for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const a=x+dx,b=y+dy;if(a>=0&&a<W&&b>=0&&b<H&&this.board[b][a]===5)marked.set(b*W+a,[a,b]);}this.marked=[...marked.values()];this.event={id:this.event.id+1,text:this.chain+' 연쇄! +'+points,chain:this.chain};this.phase='clearing';this.timer=340;return;}
 if(this.chain&&this.board.every(row=>row.every(v=>!v))){this.score+=2100;this.attack(30);this.event={id:this.event.id+1,text:'올 클리어! +2,100',chain:this.chain};}
 if(this.pending){const count=Math.min(30,this.pending);this.pending-=count;const order=[0,1,2,3,4,5];for(let i=5;i>0;i--){const j=Math.floor(this.garbageRng()*(i+1));[order[i],order[j]]=[order[j],order[i]];}for(let i=0;i<count;i++){const x=order[i%6];let y=H-1;while(y>=0&&this.board[y][x])y--;if(y<0){this.end();return;}this.board[y][x]=5;}this.phase='garbage';this.timer=260;return;}this.spawn();}
 receive(n){this.pending=Math.min(180,this.pending+Math.max(0,Math.floor(n)));}
 takeAttack(){const n=this.outgoing;this.outgoing=0;return n;}
 snapshot(){return{board:this.board.map(r=>[...r]),active:this.active?{...this.active,colors:[...this.active.colors]}:null,ghost:this.ghost(),queue:this.queue.map(p=>[...p]),score:this.score,chain:this.chain,maxChain:this.maxChain,cleared:this.cleared,pending:this.pending,elapsed:this.elapsed,phase:this.phase,marked:this.marked,event:{...this.event}};}
}
const api={W,H,Game,cells,groups,random};if(typeof module==='object'&&module.exports)module.exports=api;else root.PuyoCore=api;
})(globalThis);
