(function(){'use strict';
const $=id=>document.getElementById(id),Core=window.PuyoCore,colors=['','#eaa3bd','#a995d4','#86c9b5','#edc86e','#c9c6d3'],shades=['','#cf7c9b','#8772b7','#65a993','#ccaa4d','#aaa7b9'];
let mode='solo',solo=null,paused=false,view=null,ws=null,identity=null,busy=false,intentional=false,reconnectTimer=null,reconnectUntil=0,last=performance.now(),seq=0,lastRound=0,eventId=-1,toastTimer,stored=null,prediction=null;
const held=new Map();let best={score:0,chain:0};try{best={...best,...JSON.parse(localStorage.getItem('mongle-jelly-best')||'{}')};stored=JSON.parse(sessionStorage.getItem('mongle-jelly-room')||'null');$('nickname').value=localStorage.getItem('mongle-jelly-name')||'';}catch{}
function toast(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4500);}
function send(m){if(ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify(m));}
function record(){if(!solo)return;if(solo.score>best.score||solo.maxChain>best.chain){best.score=Math.max(best.score,solo.score);best.chain=Math.max(best.chain,solo.maxChain);try{localStorage.setItem('mongle-jelly-best',JSON.stringify(best));}catch{}}$('best').textContent=best.score.toLocaleString();$('best-chain').textContent='나의 가장 긴 연결 · '+best.chain+'연쇄';}
function localState(){return mode==='solo'?solo?.snapshot():view?.players.find(p=>p.id===identity?.you)?.game;}
function overlay(title,text,button,kicker='A LITTLE CHAIN OF JOY'){const show=title!==null;$('overlay').hidden=!show;if(!show)return;$('overlay-title').textContent=title;$('overlay-text').textContent=text;$('overlay-kicker').textContent=kicker;$('play').hidden=!button;if(button)$('play').textContent=button;}
function update(){const g=localState();$('score').textContent=(g?.score||0).toLocaleString();$('chain').textContent=(g?.maxChain||0)+' CHAIN';$('cleared').textContent=g?.cleared||0;const sec=Math.floor((g?.elapsed||0)/1000);$('time').textContent=String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0');$('incoming').textContent=g?.pending||0;$('pause').hidden=mode==='online';$('restart').hidden=mode==='online';$('tips').hidden=mode==='online';$('opponent-section').hidden=mode!=='online'||!view;$('attack-help').textContent=mode==='online'?'공격으로 대기 중인 방해를 먼저 상쇄해요. 남은 공격은 살아 있는 상대에게 순서대로 보내요.':'연쇄를 만들며 나만의 리듬을 찾아보세요.';
 if(g&&g.event.id!==eventId){eventId=g.event.id;$('feedback').textContent=g.event.text;}if(mode==='solo'){if(!solo){overlay('연결할 준비 됐나요?','같은 색 4개를 모으면 톡! 연쇄가 이어질수록 더 짜릿해요.','플레이 시작 →');$('play-state').textContent='READY TO CONNECT';}else if(solo.phase==='over'){overlay('잘 이어왔어요!',solo.score.toLocaleString()+'점 · 최대 '+solo.maxChain+'연쇄','다시 플레이 →','YOUR LITTLE RECORD');$('play-state').textContent='NICE PLAY';}else if(paused){overlay('잠깐, 쉬어갈까요?','지금의 연결을 그대로 간직하고 있어요.','이어서 플레이 →','TAKE YOUR TIME');$('play-state').textContent='PAUSED';}else{overlay(null);$('play-state').textContent='MAKE A LITTLE MAGIC';}$('pause').disabled=!solo||solo.phase==='over';return;}
 if(!view){overlay('친구들과 연결해요','위에서 방을 만들거나 초대받은 코드를 입력하세요.',null,'PLAY TOGETHER');$('play-state').textContent='ONLINE LOBBY';return;}
 if(view.phase==='waiting'){overlay('모두 준비됐나요?','준비하기를 누른 뒤 방장의 시작을 기다려주세요.',null,'WAITING FOR FRIENDS');}else if(view.phase==='countdown'){overlay(String(Math.max(1,Math.ceil((view.startAt-(view.now+performance.now()-view.receivedAt))/1000))),'같은 순서, 같은 출발. 마지막 한 명까지!',null,'GET READY');}else if(view.phase==='finished'){const winner=view.players.find(p=>p.id===view.winner);overlay(!winner?'무승부!':view.winner===identity?.you?'마지막까지 살아남았어요!':winner.name+'님의 승리!',`내 점수 ${(g?.score||0).toLocaleString()} · 최대 ${g?.maxChain||0}연쇄`,null,'ROUND COMPLETE');}else if(!ws||ws.readyState!==WebSocket.OPEN){overlay('다시 연결하고 있어요','경기는 계속 진행됩니다. 연결이 복구되면 자동으로 돌아가요.',null,'RECONNECTING');}else if(g?.phase==='over'){overlay('이번에는 여기까지!','옆에서 남은 친구들의 경기를 관전하세요.',null,'SPECTATING');}else overlay(null);$('play-state').textContent=view.phase==='playing'?'LIVE · LAST JELLY STANDING':view.phase.toUpperCase();
}
function newSolo(){solo=new Core.Game(crypto.getRandomValues(new Uint32Array(1))[0]);paused=false;held.clear();eventId=-1;record();update();$('board').focus({preventScroll:true});document.querySelector('.machine').scrollIntoView({block:'start',behavior:'smooth'});}
function togglePause(){if(mode!=='solo'||!solo||solo.phase==='over')return;paused=!paused;held.clear();record();update();}
function switchMode(next){if(next===mode)return;if(next==='solo'&&identity){if(!confirm('방에서 나가고 혼자 하기로 전환할까요?'))return;leave();}if(next==='online'&&solo){paused=true;record();}mode=next;held.clear();eventId=-1;document.body.classList.toggle('online-entry',next==='online'&&!identity);document.body.classList.toggle('online-room',next==='online'&&!!identity);$('solo-tab').setAttribute('aria-pressed',String(next==='solo'));$('online-tab').setAttribute('aria-pressed',String(next==='online'));$('online-panel').hidden=next!=='online';$('connection').textContent=next==='solo'?'● 오프라인 플레이 가능':'● 친구와 같은 방 코드로 연결';update();}
function boardValid(g,p){return Core.cells(p).every(([x,y])=>x>=0&&x<Core.W&&y>=0&&y<Core.H&&!g.board[y][x]);}
function predict(action,inputSeq){const g=localState();if(!g?.active||g.phase!=='falling')return;let p=prediction?.active?{...prediction.active,colors:[...prediction.active.colors]}:{...g.active,colors:[...g.active.colors]};if(action==='left'||action==='right'){const n={...p,x:p.x+(action==='left'?-1:1)};if(boardValid(g,n))p=n;}else if(action==='rotate'||action==='ccw'){const rotated={...p,r:(p.r+(action==='rotate'?1:3))%4};for(const [dx,dy]of [[0,0],[-1,0],[1,0],[0,-1]]){const n={...rotated,x:rotated.x+dx,y:rotated.y+dy};if(boardValid(g,n)){p=n;break;}}}else if(action==='down'){const n={...p,y:p.y+1};if(boardValid(g,n))p=n;}else if(action==='drop'){while(boardValid(g,{...p,y:p.y+1}))p.y++;}prediction={active:p,seq:inputSeq};}
function act(action){if(mode==='solo'){if(!solo||paused||solo.phase==='over')return;solo.act(action);record();}else if(view?.phase==='playing'&&localState()?.phase!=='over'&&ws?.readyState===WebSocket.OPEN){const inputSeq=++seq;predict(action,inputSeq);send({type:'input',round:view.round,seq:inputSeq,action});}}
const keymap={ArrowLeft:'left',ArrowRight:'right',ArrowDown:'down',ArrowUp:'rotate',KeyX:'rotate',KeyZ:'ccw',Space:'drop'};
document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select')||e.ctrlKey||e.metaKey||e.altKey)return;if(e.code==='KeyP'||e.code==='Escape'){if(!e.repeat){e.preventDefault();togglePause();}return;}if(e.code==='Enter'&&mode==='solo'&&(!solo||paused||solo.phase==='over')){e.preventDefault();$('play').click();return;}const action=keymap[e.code];if(!action)return;e.preventDefault();if(e.repeat)return;act(action);if(['left','right','down'].includes(action))held.set(e.code,{action,next:performance.now()+(action==='down'?60:170)});});document.addEventListener('keyup',e=>held.delete(e.code));
for(const b of document.querySelectorAll('[data-action]')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);act(b.dataset.action);if(['left','right','down'].includes(b.dataset.action))held.set('touch'+e.pointerId,{action:b.dataset.action,next:performance.now()+170});};b.onpointerup=b.onpointercancel=e=>held.delete('touch'+e.pointerId);b.onlostpointercapture=e=>held.delete('touch'+e.pointerId);}
function background(){held.clear();if(mode==='solo'&&solo&&solo.phase!=='over'){paused=true;record();update();}}
window.addEventListener('blur',background);document.addEventListener('visibilitychange',()=>{if(document.hidden)background();});window.addEventListener('beforeunload',e=>{if(identity&&['playing','countdown'].includes(view?.phase)){e.preventDefault();e.returnValue='';}});
$('play').onclick=()=>{if(mode!=='solo')return;if(paused&&solo?.phase!=='over'){paused=false;update();$('board').focus();}else newSolo();};$('pause').onclick=togglePause;$('restart').onclick=()=>{if(!solo||solo.phase==='over'||confirm('현재 기록을 마치고 새로 시작할까요?')){record();newSolo();}};$('solo-tab').onclick=()=>switchMode('solo');$('online-tab').onclick=()=>switchMode('online');
function persistRoom(){try{if(identity)sessionStorage.setItem('mongle-jelly-room',JSON.stringify({...identity,at:Date.now()}));else sessionStorage.removeItem('mongle-jelly-room');}catch{}}
function setBusy(value){busy=value;$('create-room').disabled=value;$('join-room').disabled=value;$('resume-room').disabled=value;}
function roomUI(){const r=view;document.body.classList.toggle('online-entry',mode==='online'&&!identity);document.body.classList.toggle('online-room',mode==='online'&&!!identity);$('online-panel').classList.toggle('in-play',!!r&&['countdown','playing'].includes(r.phase));$('join-form').hidden=!!identity;$('room-info').hidden=!identity;if(!r)return;$('code-label').textContent=r.code;$('seats').replaceChildren();for(const p of r.players){const el=document.createElement('div');el.className='seat'+(p.ready?' ready':'');const name=document.createElement('b');name.textContent=(p.id===r.host?'♕ ':'')+p.name+(p.id===identity.you?' · 나':'');const state=document.createElement('span');state.textContent=!p.connected?'재접속 대기':r.phase==='waiting'?(p.ready?'준비 완료':'준비 중'):p.game?.phase==='over'?'관전 중':'플레이 중';el.append(name,state);$('seats').append(el);}const me=r.players.find(p=>p.id===identity.you);$('ready-room').hidden=r.phase!=='waiting';$('ready-room').textContent=me?.ready?'준비 취소':'준비하기';$('start-room').hidden=r.phase!=='waiting'||r.host!==identity.you;$('start-room').disabled=r.players.length<2||!r.players.every(p=>p.ready&&p.connected);$('rematch-room').hidden=r.phase!=='finished'||r.host!==identity.you;$('room-message').textContent=r.phase==='waiting'?'2~4명이 모두 준비되면 방장이 시작할 수 있어요.':r.phase==='finished'?'방장이 새 대결 준비를 누르면 다시 준비할 수 있어요.':'공격은 살아 있는 상대에게 번갈아 전달돼요. 온라인에서는 일시정지되지 않아요.';
 const peers=r.players.filter(p=>p.id!==identity.you),ids=peers.map(p=>p.id).join(',');if($('opponents').dataset.ids!==ids){$('opponents').dataset.ids=ids;$('opponents').replaceChildren();for(const p of peers){const el=document.createElement('div');el.className='opponent';el.dataset.id=p.id;const name=document.createElement('p'),canvas=document.createElement('canvas'),score=document.createElement('b');canvas.width=180;canvas.height=360;el.append(name,canvas,score);$('opponents').append(el);}}for(const p of peers){const el=[...$('opponents').children].find(el=>el.dataset.id===p.id);el.className='opponent'+(p.game?.phase==='over'?' out':'')+(!p.connected?' disconnected':'');el.querySelector('p').textContent=p.name;el.querySelector('b').textContent=(p.game?.score||0).toLocaleString()+'점 · '+(p.game?.phase==='over'?'탈락':(p.game?.maxChain||0)+'연쇄');}$('alive-count').textContent=r.players.filter(p=>p.game&&p.game.phase!=='over').length+'명 생존';}
function connect(request,retry=false){if(busy&&!retry)return;setBusy(true);intentional=false;clearTimeout(reconnectTimer);let url;try{url=new URL(window.PUYO_ONLINE_SERVER||window.BLOCK_ONLINE_SERVER||location.origin);if(!['http:','https:','ws:','wss:'].includes(url.protocol))throw Error();url.protocol=url.protocol==='https:'||url.protocol==='wss:'?'wss:':'ws:';url.pathname='/puyo-ws';url.search='';url.hash='';}catch{setBusy(false);toast('게임 서버 주소 설정을 확인해주세요.');return;}
 $('connection').textContent=retry?'● 재접속 중…':'● 서버 연결 중 · 첫 연결은 잠시 걸릴 수 있어요';const socket=new WebSocket(url);ws=socket;let joined=false,failed=false;const timeout=setTimeout(()=>{if(!joined){failed=true;socket.close();setBusy(false);toast('연결이 지연되고 있어요. 잠시 후 다시 시도해주세요.');}},25000);
 socket.onopen=()=>socket.send(JSON.stringify({...request,protocol:1}));socket.onmessage=e=>{if(ws!==socket)return;let m;try{m=JSON.parse(e.data);}catch{return;}if(m.type==='joined'){joined=true;clearTimeout(timeout);setBusy(false);identity={code:m.code,you:m.you,token:m.token};persistRoom();$('connection').textContent='● 연결됨 · '+m.code;roomUI();}else if(m.type==='state'){m.receivedAt=performance.now();if(m.round!==lastRound){if(m.phase==='countdown')setTimeout(()=>document.querySelector('.machine').scrollIntoView({block:'start',behavior:'smooth'}),50);seq=0;lastRound=m.round;eventId=-1;prediction=null;held.clear();}view=m;const ack=m.players.find(p=>p.id===identity?.you)?.ack||0;seq=Math.max(seq,ack);if(prediction&&ack>=prediction.seq)prediction=null;roomUI();update();}else if(m.type==='error'){toast(m.message);if(!joined){failed=true;setBusy(false);clearTimeout(timeout);socket.close();if(retry){identity=null;view=null;persistRoom();roomUI();update();}}}else if(m.type==='left'){identity=null;view=null;persistRoom();roomUI();update();}};
 socket.onerror=()=>{};socket.onclose=()=>{clearTimeout(timeout);if(ws!==socket)return;setBusy(false);held.clear();if(intentional)return;$('connection').textContent='● 연결 끊김';if(identity&&!failed){if(joined)reconnectUntil=Date.now()+14000;if(Date.now()<reconnectUntil){reconnectTimer=setTimeout(()=>connect({type:'resume',code:identity.code,token:identity.token},true),1000);}else{toast('재접속 시간이 지났습니다. 방을 다시 만들어주세요.');identity=null;view=null;persistRoom();roomUI();}}else if(!failed)toast('온라인 서버에 연결하지 못했습니다. 서버에 젤리 대전 업데이트가 적용됐는지 확인해주세요.');update();};}
function leave(){intentional=true;clearTimeout(reconnectTimer);send({type:'leave'});ws?.close();ws=null;identity=null;view=null;seq=0;lastRound=0;held.clear();persistRoom();setBusy(false);roomUI();update();}
const name=()=>{const n=$('nickname').value.trim()||'젤리 친구';try{localStorage.setItem('mongle-jelly-name',n);}catch{}return n;};$('create-room').onclick=()=>connect({type:'create',name:name()});$('join-room').onclick=()=>{const code=$('room-code').value.trim().toUpperCase();if(!/^[A-F0-9]{6}$/.test(code)){toast('6자리 방 코드를 입력해주세요.');return;}connect({type:'join',code,name:name()});};$('room-code').onkeydown=e=>{if(e.key==='Enter')$('join-room').click();};$('ready-room').onclick=()=>send({type:'ready',ready:!view.players.find(p=>p.id===identity.you).ready});$('start-room').onclick=()=>send({type:'start'});$('rematch-room').onclick=()=>send({type:'rematch'});$('leave-room').onclick=()=>{if(['playing','countdown'].includes(view?.phase)&&!confirm('나가면 현재 대결에서 탈락합니다. 나갈까요?'))return;leave();};$('copy-room').onclick=async()=>{const u=new URL(location.href);u.search='';u.searchParams.set('room',identity.code);try{await navigator.clipboard.writeText(u.href);toast('초대 링크를 복사했어요.');}catch{prompt('초대 링크를 복사해주세요.',u.href);}};
if(stored&&Date.now()-stored.at<24*60*60*1000){$('resume-room').hidden=false;$('resume-room').onclick=()=>{reconnectUntil=Date.now()+14000;connect({type:'resume',code:stored.code,token:stored.token});};}const invited=new URLSearchParams(location.search).get('room');if(invited){$('room-code').value=invited.slice(0,6);switchMode('online');}
function jelly(ctx,x,y,s,color,alpha=1){ctx.save();ctx.globalAlpha=alpha;const cx=x+s/2,cy=y+s/2,r=s*.43;ctx.fillStyle=shades[color];ctx.beginPath();ctx.roundRect(cx-r,cy-r,s*.86,s*.87,[s*.39,s*.39,s*.3,s*.3]);ctx.fill();ctx.fillStyle=colors[color];ctx.beginPath();ctx.roundRect(cx-r,cy-r-1,s*.86,s*.78,[s*.4,s*.4,s*.3,s*.3]);ctx.fill();ctx.fillStyle='#ffffff55';ctx.beginPath();ctx.ellipse(cx-s*.16,cy-s*.23,s*.15,s*.07,-.5,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#554760';ctx.fillStyle='#554760';ctx.lineWidth=Math.max(1,s*.027);if(color===2){for(const d of [-1,1]){ctx.beginPath();ctx.arc(cx+d*s*.14,cy-s*.025,s*.045,Math.PI,0);ctx.stroke();}}else{for(const d of [-1,1]){ctx.beginPath();ctx.ellipse(cx+d*s*.14,cy-s*.03,s*.029,s*.046,0,0,Math.PI*2);ctx.fill();}}ctx.beginPath();if(color===5){ctx.moveTo(cx-s*.06,cy+s*.11);ctx.lineTo(cx+s*.06,cy+s*.11);}else if(color===4){ctx.arc(cx,cy+s*.1,s*.04,0,Math.PI*2);}else ctx.arc(cx,cy+s*.045,s*.085,0,Math.PI);ctx.stroke();ctx.restore();}
function drawBoard(canvas,g,own=false,age=0){const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,s=w/6;ctx.clearRect(0,0,w,h);ctx.fillStyle=own?'#f2edf6':'#f1ecf5';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#e4dceb';ctx.lineWidth=.6;for(let x=1;x<6;x++){ctx.beginPath();ctx.moveTo(x*s,0);ctx.lineTo(x*s,h);ctx.stroke();}for(let y=1;y<12;y++){ctx.beginPath();ctx.moveTo(0,y*s);ctx.lineTo(w,y*s);ctx.stroke();}ctx.fillStyle='#c7b4d7';ctx.font=s*.23+'px sans-serif';ctx.textAlign='center';ctx.fillText('×',2.5*s,s*.32);if(!g)return;const clear=new Set((g.marked||[]).map(([x,y])=>y*6+x));for(let y=1;y<13;y++)for(let x=0;x<6;x++)if(g.board[y][x])jelly(ctx,x*s,(y-1)*s,s,g.board[y][x],clear.has(y*6+x)?(.55+.35*Math.sin(performance.now()/55)):1);const active=own&&prediction?.active?prediction.active:g.active;if(own&&g.ghost)for(const [x,y,c]of Core.cells(g.ghost))jelly(ctx,x*s,(y-1)*s,s,c,.17);if(active){const interval=Math.max(130,850-Math.floor((g.elapsed||0)/30000)*55),canFall=boardValid(g,{...active,y:active.y+1}),offset=canFall?Math.min(.92,((g.fall||0)+age)/interval):0;for(const [x,y,c]of Core.cells(active))jelly(ctx,x*s,(y-1+offset)*s,s,c);}}
function drawNext(g){const c=$('next'),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);(g?.queue||[[1,2],[3,4],[2,3]]).forEach((p,i)=>{jelly(ctx,15+i*83,51,43,p[0]);jelly(ctx,15+i*83,10,43,p[1]);});}
let nextUI=0;function frame(now){const dt=Math.min(50,now-last);last=now;for(const [key,h]of held)if(now>=h.next){act(h.action);h.next=now+(h.action==='down'?55:90);}if(mode==='solo'&&solo&&!paused){solo.step(dt);solo.takeAttack();if(solo.phase==='over')record();}const g=localState(),networkAge=mode==='online'&&view?Math.min(100,now-view.receivedAt):0;drawBoard($('board'),g,true,networkAge);drawNext(g);if(mode==='online'&&view)for(const p of view.players){if(p.id===identity?.you)continue;const el=[...$('opponents').children].find(e=>e.dataset.id===p.id);if(el)drawBoard(el.querySelector('canvas'),p.game,false,networkAge);}if(now>=nextUI){update();nextUI=now+100;}requestAnimationFrame(frame);}record();update();requestAnimationFrame(frame);
})();
