const {test}=require('node:test'),assert=require('node:assert/strict');
const {BattleGame,attackFor}=require('../../frontend/block-battle-core.js');
const {Game,SHAPES}=require('../../frontend/block-game-core.js');
const E=require('../../frontend/block-online-engine.js');
const {Rooms}=require('../rooms.cjs');
function blank(g){g.board=Array.from({length:22},()=>Array(10).fill(null));g.status='playing';g.events=[];}
function single(g,mini=false){blank(g);g.board[20]=Array(10).fill('J');for(let x=3;x<=5;x++)g.board[20][x]=null;g.board[19][3]='J';if(!mini)g.board[19][5]='J';g.board[21][3]='J';if(mini)g.board[21][5]='J';g.piece={type:'T',m:[[0,1,0],[1,1,0],[0,1,0]],x:3,y:19,rot:3};g.lastMove='';assert.equal(g.collides(),false);assert.equal(g.rotate(1),true);}
function four(g){blank(g);g.board[10][0]='J';for(let y=18;y<22;y++){g.board[y].fill('J');g.board[y][4]=null;}g.piece={type:'I',m:[[1],[1],[1],[1]],x:4,y:18,rot:1};g.lastMove='';}
test('attack table, mini and perfect-clear replacement exactly match selected rules',()=>{assert.deepEqual([0,1,2,3,4].map(n=>attackFor(n,'',false)),[0,0,1,2,4]);assert.deepEqual([0,1,2,3].map(n=>attackFor(n,'full',false)),[0,2,4,6]);assert.equal(attackFor(0,'mini',false),0);assert.equal(attackFor(1,'mini',false),1);assert.equal(attackFor(4,'',true),10);assert.equal(attackFor(2,'full',true),10);});
test('real rotation into full/mini single; double/triple; no spin without rotation',()=>{let g=new BattleGame();single(g);g.hardDrop();assert.equal(g.lastAttack.spin,'full');assert.equal(g.lastAttack.lines,1);assert.equal(g.lastAttack.attack,2);
 g=new BattleGame();single(g,true);g.hardDrop();assert.equal(g.lastAttack.spin,'mini');assert.equal(g.lastAttack.attack,1);
 g=new BattleGame();single(g);g.lastMove='move';g.hardDrop();assert.equal(g.lastAttack.spin,'');assert.equal(g.lastAttack.attack,0);
 g=new BattleGame();blank(g);g.board[19][3]='J';g.board[20].fill('J');g.board[21].fill('J');for(let x=3;x<6;x++)g.board[20][x]=null;g.board[21][4]=null;g.piece={type:'T',m:[[0,1,0],[0,1,1],[0,1,0]],x:3,y:19,rot:1};assert.equal(g.rotate(1),true);g.hardDrop();assert.equal(g.lastAttack.lines,2);assert.equal(g.lastAttack.attack,4);
 g=new BattleGame();blank(g);g.piece={type:'T',m:SHAPES.T.map(r=>r.slice()),x:4,y:16,rot:0};for(let y=18;y<21;y++){g.board[y].fill('J');g.board[y][4]=null;}g.board[19][5]=null;g.board[16][4]='J';assert.equal(g.collides(),false);assert.equal(g.rotate(1),true);assert.equal(g.lastKick,4);g.hardDrop();assert.equal(g.lastAttack.lines,3);assert.equal(g.lastAttack.attack,6);
});
test('perfect clear is total ten; hard drop translation invalidates old rotation; garbage topout',()=>{let g=new BattleGame();blank(g);for(let y=20;y<22;y++){g.board[y].fill('J');g.board[y][4]=g.board[y][5]=null;}g.piece={type:'O',m:SHAPES.O,x:4,y:20,rot:0};g.hardDrop();assert.equal(g.lastAttack.allClear,true);assert.equal(g.lastAttack.attack,10);
 g=new BattleGame();g.lastMove='rotate';g.hardDrop();assert.equal(g.lastAttack.spin,'');
 g=new BattleGame();blank(g);g.board[0][0]='T';g.addGarbage([4]);assert.equal(g.status,'over');assert.equal(g.reason,'garbage');assert.equal(g.board[21].filter(Boolean).length,9);assert.equal(g.board[21][4],null);
});
function battle(n=3){let now=10000;const r=new Rooms({now:()=>now}),cs=Array.from({length:n},()=>({send(){}}));const room=r.create(cs[0],'A','battle');for(let i=1;i<n;i++)r.join(cs[i],room.code,'P'+i);for(const c of cs)r.ready(c,true);r.start(cs[0]);now+=3000;r.tick();return{r,cs,room,advance(ms){now+=ms;r.tick();}};}
test('cancellation, round-robin target, delayed garbage, no score-mode attacks',()=>{const s=battle(),[a,b,c]=s.cs;a.player.incoming=[{lines:2,hole:0,readyAt:0}];four(a.player.game);s.r.input(a,{round:1,seq:1,action:'drop'});assert.equal(a.player.cancelled,2);assert.equal(a.player.sent,2);assert.equal(b.player.incoming[0].lines,2);assert.equal(c.player.incoming.length,0);
 s.advance(20);four(a.player.game);s.r.input(a,{round:1,seq:2,action:'drop'});assert.equal(c.player.incoming[0].lines,4);assert.equal(b.player.game.board.some(row=>row.includes('G')),false);
 s.r.input(b,{round:1,seq:1,action:'drop'});assert.equal(b.player.game.board.some(row=>row.includes('G')),false);s.advance(1050);s.r.input(b,{round:1,seq:2,action:'drop'});assert.ok(b.player.game.board.some(row=>row.includes('G')));assert.equal(b.player.incoming.length,0);
 const g=new Game();assert.equal(g.events,undefined);assert.equal(g.rules,undefined);
});
test('battle has no 3m cutoff, survival ranks and rematch; simultaneous last deaths draw',()=>{const s=battle();assert.equal(s.room.endAt,0);s.advance(180001);assert.equal(s.room.phase,'playing');const [a,b,c]=s.cs;a.player.game.end('topout');s.advance(10);b.player.game.end('topout');s.advance(10);assert.equal(s.room.phase,'finished');assert.deepEqual(s.room.winnerIds,[c.player.id]);assert.equal(c.player.game.reason,'win');assert.deepEqual(s.r.view(c).players.map(p=>p.id),[c.player.id,b.player.id,a.player.id]);s.r.rematch(a);assert.equal(s.room.mode,'battle');assert.ok(s.room.players.every(p=>p.game===null&&!p.ready));for(const p of s.cs)s.r.ready(p,true);s.r.start(a);assert.ok(s.room.players.every(p=>p.incoming.length===0&&p.sent===0&&p.finishAt===null));
 const t=battle(2);for(const p of t.cs)p.player.game.end('topout');t.advance(1);assert.equal(t.room.phase,'finished');assert.deepEqual(t.room.winnerIds,[]);assert.deepEqual(t.r.view(t.cs[0]).players.map(p=>p.rank),[1,1]);
});
test('battle snapshot predicts wall kicks, hold, RNG and attacks after restore',()=>{const a=new BattleGame({seed:'BATTLE'});single(a);const b=E.restore(E.snapshot(a));E.apply(a,'drop');E.apply(b,'drop');assert.deepEqual(E.snapshot(a),E.snapshot(b));assert.equal(b.lastAttack.attack,2);for(let i=0;i<20;i++){blank(a);a.spawn();const c=E.restore(E.snapshot(a));for(const action of ['left','rotate','ccw','hold','drop']){E.apply(a,action);E.apply(c,action);}assert.deepEqual(E.snapshot(a),E.snapshot(c));}});
test('uneven team battle starts, attacks enemies only and awards the surviving team',()=>{let now=50000;const r=new Rooms({now:()=>now}),cs=Array.from({length:4},()=>({send(){}}));const room=r.create(cs[0],'R','team');for(let i=1;i<4;i++)r.join(cs[i],room.code,'P'+i);
 for(const c of cs)r.setTeam(c,c===cs[0]?'red':'blue');for(const c of cs)r.ready(c,true);r.start(cs[0]);now+=3000;r.tick();assert.equal(room.phase,'playing');assert.deepEqual(room.players.map(p=>p.team),['red','blue','blue','blue']);
 four(cs[0].player.game);r.input(cs[0],{round:1,seq:1,action:'drop'});assert.equal(cs[1].player.incoming[0].lines,4);assert.equal(cs[2].player.incoming.length,0);assert.equal(cs[3].player.incoming.length,0);
 now+=20;four(cs[0].player.game);r.input(cs[0],{round:1,seq:2,action:'drop'});assert.equal(cs[2].player.incoming[0].lines,4);assert.ok(room.players.filter(p=>p.team==='red').every(p=>p.incoming.length===0));
 for(const c of cs.slice(1))c.player.game.end('topout');now+=1;r.tick();assert.equal(room.phase,'finished');assert.equal(room.winnerTeam,'red');assert.deepEqual(room.winnerIds,[cs[0].player.id]);assert.equal(r.view(cs[0]).players[0].rank,1);
});
test('team battle accepts any split but requires at least one player on each team',()=>{let now=70000;const r=new Rooms({now:()=>now}),a={send(){}},b={send(){}};const room=r.create(a,'A','team');r.join(b,room.code,'B');r.setTeam(a,'red');r.setTeam(b,'red');r.ready(a,true);r.ready(b,true);assert.throws(()=>r.start(a),/최소 1명/);r.setTeam(b,'blue');assert.equal(b.player.ready,false);r.ready(b,true);r.start(a);assert.equal(room.endAt,0);});
