'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {generate,options,nextCell,DIRS}=require('../maze-core.cjs');
const {MazeRooms}=require('../maze-rooms.cjs');
function path(map,destination=map.exit){const parents=new Map([[map.start,null]]),queue=[map.start];for(let h=0;h<queue.length;h++){const i=queue[h];for(let d=0;d<4;d++){const n=nextCell(map,i,d);if(!parents.has(n)){parents.set(n,[i,d]);queue.push(n);}}}const route=[];for(let i=destination;i!==map.start;){const [prev,d]=parents.get(i);route.unshift(d);i=prev;}return route;}
function setup(n=4,settings={width:9,height:11,items:true,extreme:true}){let clock=10000;const manager=new MazeRooms({now:()=>clock}),clients=Array.from({length:n},()=>({send(){}}));const room=manager.create(clients[0],'host',settings);for(let i=1;i<n;i++)manager.join(clients[i],room.code,'P'+i);return{manager,clients,room,advance(ms){clock+=ms;manager.tick();},start(){for(const c of clients)manager.ready(c,true);manager.start(clients[0]);clock+=3000;manager.tick();},walk(c,route){for(let i=0;i<route.length;){clock+=120;const steps=c.player.steps;manager.input(c,{round:room.round,seq:c.player.seq+1,direction:route[i]});const moved=c.player.steps-steps;assert.ok(moved>0);i+=moved;}}};}
function corridor(){const s=setup(2,{width:9,height:9});s.start();const cells=Array(81).fill(0);for(const [a,b,d] of [[0,1,1],[1,2,1],[2,11,2],[11,20,2],[20,21,1],[21,22,1],[21,30,2]]){cells[a]|=DIRS[d].bit;cells[b]|=DIRS[d].opposite;}s.room.map={width:9,height:9,cells,start:0,exit:80,traps:[]};return s;}
test('one press instantly dashes on one axis; stops at corners, first junction and dead ends',()=>{const s=corridor(),a=s.clients[0],p=a.player;s.manager.input(a,{round:1,seq:1,direction:1});assert.equal(p.cell,2);assert.equal(p.steps,2);s.advance(1000);assert.equal(p.cell,2);s.manager.input(a,{round:1,seq:2,direction:2});assert.equal(p.cell,20);s.advance(100);s.manager.input(a,{round:1,seq:3,direction:1});assert.equal(p.cell,21);assert.equal(p.direction,-1);s.advance(1000);assert.equal(p.cell,21);s.manager.input(a,{round:1,seq:4,direction:1});assert.equal(p.cell,22);s.advance(1000);assert.equal(p.cell,22);
 s.manager.input(a,{round:1,seq:5,direction:3});assert.equal(p.cell,21);assert.equal(p.direction,-1);
});
test('dash checks intermediate traps and exits and never resumes without a new press',()=>{for(const kind of ['trap','exit','stop','disconnect','wall']){const s=corridor(),a=s.clients[0],p=a.player;if(kind==='trap')s.room.map.traps=[1];if(kind==='exit')s.room.map.exit=1;s.manager.input(a,{round:1,seq:1,direction:kind==='wall'?0:1});if(kind==='stop')s.manager.input(a,{round:1,seq:2,direction:-1});if(kind==='disconnect')s.manager.disconnect(a);for(let i=0;i<20;i++)s.advance(110);assert.equal(p.cell,kind==='trap'||kind==='wall'?0:kind==='exit'?1:2);assert.equal(p.direction,-1);if(kind==='trap')assert.ok(p.consumed.has(1));if(kind==='exit')assert.equal(p.status,'finished');}});
test('maze dimensions, deterministic generation, reciprocal walls, reachability, optional traps off solution',()=>{for(const [w,h] of [[9,9],[10,12],[21,15],[81,9],[9,81],[81,81]])for(let seed=1;seed<=8;seed++){const map=generate({width:w,height:h,items:true},seed);assert.deepEqual(map,generate({width:w,height:h,items:true},seed));const visited=new Set([0]),q=[0];for(let j=0;j<q.length;j++){const i=q[j];DIRS.forEach((d,dir)=>{if(!(map.cells[i]&d.bit))return;const x=i%w+d.dx,y=Math.floor(i/w)+d.dy;assert.ok(x>=0&&x<w&&y>=0&&y<h);const n=nextCell(map,i,dir);assert.ok(map.cells[n]&d.opposite);if(!visited.has(n)){visited.add(n);q.push(n);}});}assert.equal(visited.size,w*h);let i=0;for(const d of path(map)){i=nextCell(map,i,d);assert.ok(!map.traps.includes(i));}assert.equal(i,map.exit);}
 for(const width of [0,8,82,9.5,NaN,Infinity,'21'])assert.throws(()=>options({width,height:10}));assert.deepEqual(generate({width:9,height:9,items:false},1).traps,[]);
});
test('host settings, reset readiness, countdown locking, no time limit, short taps and authoritative movement',()=>{const s=setup();assert.throws(()=>s.manager.settings(s.clients[1],{width:10,height:10}));s.manager.ready(s.clients[0],true);s.manager.settings(s.clients[0],{width:10,height:12});assert.equal(s.clients[0].player.ready,false);s.start();assert.throws(()=>s.manager.settings(s.clients[0],{width:20,height:20}));const c=s.clients[0],dir=path(s.room.map)[0];s.manager.input(c,{round:0,seq:1,direction:dir});assert.equal(c.player.cell,0);s.manager.input(c,{round:1,seq:1,direction:dir});const moved=c.player.cell;assert.notEqual(moved,0);s.manager.input(c,{round:1,seq:2,direction:dir,cell:10000});assert.equal(c.player.cell,moved);s.manager.input(c,{round:1,seq:3,direction:-1});s.advance(500000);assert.equal(s.room.phase,'playing');assert.equal(c.player.cell,moved);
 const t=setup(2);t.start();t.manager.input(t.clients[0],{round:1,seq:1,direction:0});assert.equal(t.clients[0].player.cell,0);
});
test('finish ranks, spectator focus, fog, personal reset traps, and new maze on rematch',()=>{const s=setup();s.start();const [a,b,c,d]=s.clients,firstMap=s.room.map;const full=s.manager.view(a);assert.equal(full.map,firstMap);assert.equal(s.manager.view(a).map,null);b.player.cell=firstMap.exit;assert.equal(s.manager.view(a).players.find(p=>p.id===b.player.id).cell,null);b.player.cell=0;
 if(firstMap.traps.length){s.walk(a,path(firstMap,firstMap.traps[0]));assert.equal(a.player.cell,0);assert.ok(a.player.consumed.has(firstMap.traps[0]));assert.equal(b.player.consumed.size,0);}
 s.walk(a,path(firstMap));assert.equal(a.player.status,'finished');assert.equal(s.room.phase,'playing');assert.equal(s.manager.view(a).players.find(p=>p.id===a.player.id).rank,1);s.manager.watch(a,c.player.id);assert.equal(s.manager.view(a).watchId,c.player.id);s.walk(b,path(firstMap));assert.equal(s.manager.view(b).players.find(p=>p.id===b.player.id).rank,2);s.manager.giveup(c);s.manager.giveup(d);assert.equal(s.room.phase,'finished');s.manager.rematch(a);assert.equal(s.room.map,null);s.start();assert.equal(s.room.round,2);assert.notEqual(s.room.map.seed,firstMap.seed);assert.ok(s.room.players.every(p=>p.steps===0&&p.consumed.size===0));
});
test('reconnect resends maze; countdown disconnect resets ready; timeout DNF and host migration',()=>{const s=setup(2);for(const c of s.clients)s.manager.ready(c,true);s.manager.start(s.clients[0]);s.manager.disconnect(s.clients[1]);assert.equal(s.room.phase,'waiting');assert.ok(s.room.players.every(p=>!p.ready));const replacement={send(){}};s.manager.resume(replacement,s.room.code,s.room.players[1].token);s.clients[1]=replacement;s.start();s.manager.view(replacement);const p=replacement.player;s.manager.disconnect(replacement);s.advance(1000);const restored={send(){}};s.manager.resume(restored,s.room.code,p.token);assert.ok(s.manager.view(restored).map);s.manager.disconnect(s.clients[0]);s.advance(21000);assert.equal(s.room.players[0].status,'dnf');assert.equal(s.room.host,p.id);s.manager.giveup(restored);assert.equal(s.room.phase,'finished');});
