'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),{Game,groups,cells}=require('../../frontend/puyo-core.js'),{PuyoRooms}=require('../puyo-service.cjs');
const settle=g=>{for(let n=0;n<300&&g.phase!=='falling'&&g.phase!=='over';n++)g.step(50);};
const empty=g=>{g.board=Array.from({length:13},()=>Array(6).fill(0));g.active=null;g.chain=0;g.phase='settling';g.timer=0;};
test('four orthogonal colors clear; diagonal and garbage groups do not',()=>{const g=new Game(1);empty(g);for(let i=0;i<4;i++)g.board[12-i][i]=1;assert.equal(groups(g.board).cells.length,0);g.board[12]=[2,2,2,2,5,5];assert.equal(groups(g.board).cells.length,4);g.scan();assert(g.marked.some(([x,y])=>x===4&&y===12));assert(!g.marked.some(([x,y])=>x===5&&y===12));});
test('two-chain gravity sequence scores and emits attack without erasing unrelated cells',()=>{const g=new Game(1);empty(g);g.board[12]=[1,1,1,2,0,4];g.board[11]=[2,2,1,0,0,0];g.board[10][2]=2;settle(g);assert.equal(g.maxChain,2);assert.equal(g.cleared,8);assert.equal(g.score,360);assert.equal(g.takeAttack(),5);assert.equal(g.board[12][5],4);assert.equal(g.phase,'falling');});
test('all-clear attack first cancels pending garbage and leaves no residue',()=>{const g=new Game(2);empty(g);g.board[12]=[1,1,1,1,0,0];g.receive(12);settle(g);assert.equal(g.score,2140);assert.equal(g.pending,0);assert.equal(g.takeAttack(),18);assert(g.board.every(r=>r.every(x=>x===0)));});
test('garbage distributes evenly in capped waves, with overflow losing safely',()=>{const g=new Game(3);empty(g);g.receive(35);settle(g);assert.equal(g.pending,5);assert.equal(g.board.flat().filter(x=>x===5).length,30);for(let x=0;x<6;x++)assert.equal(g.board.map(r=>r[x]).filter(Boolean).length,5);empty(g);g.board=Array.from({length:13},()=>Array(6).fill(5));g.receive(1);settle(g);assert.equal(g.phase,'over');});
test('seeded pieces are identical, rotations never escape bounds, hard drop settles separated pair',()=>{const a=new Game(99),b=new Game(99);assert.deepEqual(a.snapshot(),b.snapshot());for(let n=0;n<12;n++)a.act('left');assert.equal(a.active.x,0);for(let n=0;n<20;n++){a.act('rotate');assert(cells(a.active).every(([x,y])=>x>=0&&x<6&&y>=0&&y<13));}empty(a);a.board[12][0]=3;a.active={x:0,y:3,r:1,colors:[1,2]};a.phase='falling';a.act('drop');assert.equal(a.board[11][0],1);assert.equal(a.board[12][1],2);});
test('spawn collision loses and inputs cannot change a finished board',()=>{const g=new Game(1);g.board[1][2]=1;g.spawn();assert.equal(g.phase,'over');const before=g.snapshot();assert.equal(g.act('drop'),false);g.step(100);assert.deepEqual(g.snapshot(),before);});
function room(){let t=1000;const m=new PuyoRooms({now:()=>t,countdown:100,grace:500});const c=[{},{},{},{}];const r=m.create(c[0],'A');for(let i=1;i<4;i++)m.join(c[i],r.code,'P'+i);return {m,c,r,advance:n=>{t+=n;m.tick();}};}
test('rooms enforce capacity, host/ready gates, same seed and untrusted input',()=>{const {m,c,r,advance}=room();assert.throws(()=>m.join({},r.code,'Fifth'));assert.throws(()=>m.start(c[0]));for(const p of c)m.ready(p,true);assert.throws(()=>m.start(c[1]));m.start(c[0]);assert.equal(r.phase,'countdown');advance(101);assert.equal(r.phase,'playing');assert.deepEqual(r.players[0].game.queue,r.players[3].game.queue);const g=c[0].player.game;const x=g.active.x;m.input(c[0],{round:0,seq:1,action:'left'});assert.equal(g.active.x,x);m.input(c[0],{round:r.round,seq:1,action:'left',score:99999,board:[]});assert.equal(g.active.x,x-1);assert.equal(g.score,0);m.input(c[0],{round:r.round,seq:1,action:'left'});assert.equal(g.active.x,x-1);assert(!JSON.stringify(m.view(c[1])).includes(c[0].player.token));});
test('attacks route once across living opponents, disconnect grace/resume, winner and rematch',()=>{const {m,c,r,advance}=room();for(const p of c)m.ready(p,true);m.start(c[0]);advance(101);c[0].player.game.outgoing=4;advance(16);assert.equal(c[1].player.game.pending,4);c[0].player.game.outgoing=3;advance(16);assert.equal(c[2].player.game.pending,3);const token=c[1].player.token,id=c[1].player.id;m.disconnect(c[1]);const replacement={};m.resume(replacement,r.code,token);assert.equal(replacement.player.id,id);assert.throws(()=>m.resume({},r.code,token));m.disconnect(replacement);advance(501);assert.equal(r.players[1].game.phase,'over');r.players[2].game.end();r.players[3].game.end();advance(16);assert.equal(r.phase,'finished');assert.equal(r.winner,c[0].player.id);m.rematch(c[0]);assert.equal(r.phase,'waiting');assert(r.players.every(p=>!p.ready&&p.game===null));});
test('simultaneous loss is a draw',()=>{const m=new PuyoRooms({now:()=>10,countdown:0}),a={},b={};const r=m.create(a,'a');m.join(b,r.code,'b');m.ready(a,true);m.ready(b,true);m.start(a);a.player.game.end();b.player.game.end();m.tick();assert.equal(r.phase,'finished');assert.equal(r.winner,null);});
