const {test}=require('node:test');
const assert=require('node:assert/strict');
const {Rooms}=require('../rooms.cjs');
const {Game}=require('../../frontend/block-game-core.js');
const E=require('../../frontend/block-online-engine.js');
function setup(n=4){let clock=100000;const rooms=new Rooms({now:()=>clock});const clients=Array.from({length:n},()=>({send(){}}));const room=rooms.create(clients[0],'용욱');for(let i=1;i<n;i++)rooms.join(clients[i],room.code,'친구 '+i);return{rooms,room,clients,advance(ms){clock+=ms;rooms.tick();}};}
test('2–4 seats, host-only synchronized countdown, identical piece streams',()=>{const s=setup();assert.throws(()=>s.rooms.join({send(){}},s.room.code,'다섯째'));assert.throws(()=>s.rooms.start(s.clients[0]));for(const c of s.clients)s.rooms.ready(c,true);assert.throws(()=>s.rooms.start(s.clients[1]));s.rooms.start(s.clients[0]);assert.equal(s.room.phase,'countdown');s.advance(2999);assert.equal(s.room.phase,'countdown');s.advance(1);assert.equal(s.room.phase,'playing');const g=s.clients[0].player.game;for(const c of s.clients){assert.deepEqual(c.player.game.queue,g.queue);assert.equal(c.player.game.seed,g.seed);}assert.equal(s.room.endAt-s.room.startAt,180000);});
test('server score authority, duplicate and late input rejection, tied ranks',()=>{const s=setup(2);for(const c of s.clients)s.rooms.ready(c,true);s.rooms.start(s.clients[0]);s.advance(3000);const a=s.clients[0],b=s.clients[1],round=s.room.round;const msg={seq:1,round,action:'drop',score:99999999};s.rooms.input(a,msg);const score=a.player.game.score;assert.ok(score>0&&score<100);s.rooms.input(a,msg);assert.equal(a.player.game.score,score);s.rooms.input(b,msg);assert.equal(b.player.game.score,score);assert.deepEqual(s.rooms.view(a).players.map(p=>p.rank),[1,1]);s.advance(180000);assert.equal(s.room.phase,'finished');s.rooms.input(a,{seq:2,round,action:'drop'});assert.equal(a.player.game.score,score);assert.equal(a.player.game.reason,'time');s.rooms.rematch(a);assert.equal(s.room.phase,'waiting');assert.ok(s.room.players.every(p=>!p.ready&&p.game===null));});
test('topout spectates, reconnect preserves board and timer, host migration',()=>{const s=setup(2);for(const c of s.clients)s.rooms.ready(c,true);s.rooms.start(s.clients[0]);s.advance(3000);const [a,b]=s.clients,token=a.player.token,id=a.player.id,start=s.room.startAt;a.player.game.end('topout');s.advance(10);assert.equal(s.room.phase,'playing');s.rooms.disconnect(a);assert.equal(s.room.host,b.player.id);s.advance(300);const replacement={send(){}};s.rooms.resume(replacement,s.room.code,token);assert.equal(replacement.player.id,id);assert.equal(replacement.player.game.reason,'topout');assert.equal(s.room.startAt,start);assert.throws(()=>s.rooms.resume({send(){}},s.room.code,'bad-token'));});
test('disconnection during countdown cancels; expiry ends play; final ranks stay',()=>{const s=setup(2);for(const c of s.clients)s.rooms.ready(c,true);s.rooms.start(s.clients[0]);s.rooms.disconnect(s.clients[1]);assert.equal(s.room.phase,'waiting');assert.ok(s.room.players.every(p=>!p.ready&&!p.game));s.advance(21000);assert.equal(s.room.players.length,1);
 const t=setup(2);for(const c of t.clients)t.rooms.ready(c,true);t.rooms.start(t.clients[0]);t.advance(3000);const departed=t.clients[1].player;departed.game.score=100;t.rooms.disconnect(t.clients[1]);t.advance(21000);assert.equal(departed.game.reason,'disconnect');t.rooms.finish(t.room);t.advance(500);assert.equal(t.rooms.view(t.clients[0]).players.length,2);assert.equal(t.rooms.view(t.clients[0]).players[0].score,100);});
test('client reconstruction predicts hold/drop across new bags accurately',()=>{const a=new Game({seed:'NET'});for(let i=0;i<60;i++){// Clear board in this fixture so many bags can be checked without topout.
 a.board=Array.from({length:22},()=>Array(10).fill(null));a.spawn();const b=E.restore(E.snapshot(a));for(const action of ['hold','left','rotate','drop','right','drop']){E.apply(a,action);E.apply(b,action);}assert.deepEqual(E.snapshot(a),E.snapshot(b));}});
